import { StyleSheet, Platform } from 'react-native';
import {colors} from '~/constants/colors'

export default StyleSheet.create({
    scrollContainer:{
        flexGrow:1,
        backgroundColor: '#f0f0f0',
    },
    container:{
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor:colors.white,
    },
    logo:{
        width: 200,
        height: 100,
        marginBottom: 20,
    },
    title:{
        fontSize: 24,
        fontWeight: 'bold',
        color: colors.Vermelho,
        marginBottom: 10,
    },
    subtitle:{
        fontSize: 18,
        color: colors.black,
        marginBottom: 20,
        marginHorizontal: 20,
        flexWrap: 'wrap',
        textAlign: 'justify',
    },
    input: {
        height: 50,
        width: '90%',
        borderColor: colors.Vermelho,
        borderWidth: 1,
        borderRadius: 5,
        paddingHorizontal: 10,
        marginBottom: 10,
    },
    picker: {
        height: 50,
        width: '90%',
        borderColor: colors.Vermelho,
        borderWidth: 1,
        borderRadius: 5,
        marginBottom: 10,
        backgroundColor: colors.white,
    },
    button:{
        backgroundColor: colors.white,
        borderRadius: 5,
        width: '90%',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
        borderWidth: 1,
        borderColor: colors.Vermelho,
    },
    card: {
        backgroundColor: colors.white,
        borderRadius: 5,
        padding: 20,
        marginBottom: 10,
        width: '90%',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    label: {
        fontSize: 16,
        color: colors.black,
        marginBottom: 5,
    },
    checkboxContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
        width: '90%',
    },
    checkboxLabel: {
        fontSize: 16,
        color: colors.black,
        marginLeft: 10,
    },
    addButton: {
        backgroundColor: colors.Vermelho,
        borderRadius: 5,
        padding: 10,
        width: '90%',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
    },
    addButtonText: {
        color: colors.white,
        fontSize: 16,
        fontWeight: 'bold',
    },
})